### PR TITLE
Convert to CSS

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by marvindanig** [comment]
I'll wait on this one 'cuz a lot of what is left in here is going to go away.

**Comment by DanielRuf** [comment]
Let me know when you push new changes so I can rebase my PR then.

**Comment by marvindanig** [comment]
I moved all the old rulesets away, including those that were scss originally. Feel free to review & close this PR if we don't require it anymore.

**Comment by DanielRuf** [comment]
I have rebased and updated the last file with the needed changes.

**Comment by marvindanig** [comment]
✅ Thanks!

**Pull request merged**
