### PR TITLE
Use GitHub Actions

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
@marvindanig don't forget to signup for the GHA beta so this can be used =)

**Comment by DanielRuf** [comment]
@marvindanig don't forget to signup for the GHA beta so this can be actually used =)

**Comment by marvindanig** [comment]
i just did. 

the badge is currently not showing up on the readme, but this isn’t a priority at this time.

**Comment by DanielRuf** [comment]
This is because GHA is not yet available for this repo.

**Pull request merged**
